### ISSUE TITLE
Analytics should respect physical_naming_strategy

### ISSUE THREAD

**Issue by manosbatsis** [yahoo/elide-spring-boot-example#66]
My Spring config fragment:

```
spring:
    jpa:
        #...
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                #...
                physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
```

My JPA entity (kotlin):

```
@Entity
@Include(rootLevel = true, name = "transfer", description = "A monetary transfer transaction")
class TransferTransaction(
   // ...
)
```

My join definition in my `reservestats` hjson table:

```
joins: [
    {
        name: reserveTransfer
        to: transfer
        # Full Join is not supported for: H2
        # type: full
        definition: '{{$reserveId}} = {{reserveTransfer.$id}}'
    }
]
```

Generates: 

SELECT count(`_reservestats_reserveTransfer_138211222`.`id`) AS `count`
FROM `currency_reserve` AS `_reservestats`
LEFT OUTER JOIN `TransferTransaction` AS `_reservestats_reserveTransfer_138211222`
ON `_reservestats`.`id` = `_reservestats_reserveTransfer_138211222`.`reserve`

It should generate:

SELECT count(`_reservestats_reserveTransfer_138211222`.`id`) AS `count` 
FROM `currency_reserve` AS `_reservestats` 
   LEFT OUTER JOIN `transfer_transaction` AS `_reservestats_reserveTransfer_138211222` 
   ON `_reservestats`.`id` = `_reservestats_reserveTransfer_138211222`.`reserve_id`
